import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ['400', '700'], // 400 para normal, 700 para negrito
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
    className="h-full">
      <body
        className={`${openSans.className} antialiased h-full flex flex-col`}
      >
        <Header></Header>
        <main className="flex-1 p-10">
        {children}
      </main>
      </body>
    </html>
  );
}
